import { StyleSheet } from "react-native";
// HELPERS
import colors from "../../Helpers/Colors";

const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: colors.background,
	},
	headerWrapper: {
		paddingTop: 20,
		alignItems: "center",
		flexDirection: "row",
		paddingHorizontal: 20,
		justifyContent: "space-between",
	},
	profileImage: {
		width: 40,
		height: 40,
		borderRadius: 50,
	},
	titleWrapper: {
		marginTop: 20,
		paddingHorizontal: 20,
	},
	title: {
		fontSize: 16,
		lineHeight: 20,
		color: colors.textDark,
		fontFamily: "Montserrat-Regular",
	},
	subTitle: {
		marginTop: 5,
		fontSize: 32,
		lineHeight: 39,
		fontWeight: "700",
		color: colors.textDark,
		fontFamily: "Montserrat-Bold",
	},
	searchWrapper: {
		marginTop: 25,
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 20,
	},
	searchText: {
		flex: 1,
		color: colors.textDark,
		marginLeft: 10,
		fontFamily: "Montserrat-Semibold",
	},
	searchLine: {
		flex: 1,
		height: 2,
		marginHorizontal: 20,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: colors.textLight,
	},
	serachFocusLine: {
		flex: 1,
		width: 100,
		height: 2,
		backgroundColor: colors.primary,
	},
	categoryWrapper: {
		marginTop: 20,
		paddingHorizontal: 20,
	},
	categoryTitle: {
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "700",
		color: colors.textDark,
		fontFamily: "Montserrat-Bold",
	},
	categoryCard: {
		width: 105,
		height: 177,
		elevation: 5,
		shadowRadius: 5,
		marginRight: 20,
		borderRadius: 20,
		shadowOpacity: 0.5,
		marginVertical: 20,
		alignItems: "center",
		flexDirection: "column",
		justifyContent: "center",
		shadowColor: "rgb(0, 0, 0)",
		shadowOffset: { width: 3, height: 3 },
	},
	categoryCardTitle: {
		marginTop: 5,
		fontSize: 14,
		lineHeight: 17,
		fontWeight: "600",
		color: colors.textDark,
		fontFamily: "Montserrat-Bold",
	},
	categoryCardRightIconContainer: {
		width: 26,
		height: 26,
		marginTop: 20,
		borderRadius: 50,
		alignItems: "center",
		justifyContent: "center",
	},
	popularWrapper: {
		marginTop: 25,
		paddingHorizontal: 20,
	},
	popularTitle: {
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "700",
		color: colors.textDark,
		fontFamily: "Montserrat-Bold",
	},
	popularCardWrapper: {
		marginTop: 20,
		flexDirection: "column",
	},
	popularCard: {
		height: 161,
		elevation: 2,
		shadowRadius: 5,
		borderRadius: 20,
		marginBottom: 20,
		shadowOpacity: 0.5,
		overflow: "hidden",
		flexDirection: "row",
		alignItems: "flex-end",
		shadowColor: "rgb(0, 0, 0)",
		backgroundColor: colors.background,
		shadowOffset: { width: 3, height: 3 },
	},
	popularCardDataContainer: {
		width: "50%",
	},
	popularCardTopOfWeekContainer: {
		marginTop: 24,
		marginLeft: 20,
		flexDirection: "row",
		alignItems: "center",
	},
	popularCardTopOfWeekText: {
		fontSize: 14,
		marginLeft: 8,
		lineHeight: 17,
		fontWeight: "700",
		color: colors.textDark,
		fontFamily: "Montserrat-Bold",
	},
	popularCardTitleAndWeightContainer: {
		marginTop: 20,
		marginLeft: 20,
	},
	popularCardTitleText: {
		fontSize: 14,
		lineHeight: 17,
		fontWeight: "700",
		color: colors.textDark,
		fontFamily: "Montserrat-Bold",
	},
	popularCardWeightText: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "500",
		color: colors.textLight,
		fontFamily: "Montserrat-Bold",
	},
	popularCardPlusAndRatingContainer: {
		marginTop: 14,
		flexDirection: "row",
		alignItems: "center",
	},
	popularCardPlusContainer: {
		overflow: "hidden",
		alignItems: "center",
		justifyContent: "center",
		borderTopRightRadius: 20,
	},
	popularCardPlusPressable: {
		width: 90,
		height: 53,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: colors.primary,
	},
	popularCardRatingContainer: {
		height: 53,
		marginLeft: 20,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
	},
	popularCardRatingText: {
		fontSize: 12,
		marginLeft: 5,
		lineHeight: 15,
		fontWeight: "600",
		color: colors.textDark,
	},
	popularCardImageWrapper: {
		width: "50%",
	},
	popularCardImage: {
		width: 210,
		height: 130,
		marginBottom: 10,
	},
});

export default styles;
